import { register, login, decodeSession } from "./auth.service.js";
import { getMe, updateUser } from "./user.service.js";
import { getAllGroups, getGroupById, createGroup, updateGroup, deleteGroup, setupPrimaryGroup } from "./group.service.js";
import { getAllCategories, getCategoryById, createCategory, updateCategory, deleteCategory } from "./category.service.js";
import { getAllProducts, getProductById, createProduct, updateProduct, deleteProduct, convertGroupPrices } from "./product.service.js";
import { getAllOrders, getOrderById, createOrder, updateOrder, deleteOrder } from "./order.service.js";
import { getAllInventory, getInventoryById, upsertInventory, updateInventory, deleteInventory } from "./inventory.service.js";
import { getAllWishlists, getWishlistById, createWishlist, updateWishlist, deleteWishlist } from "./wishlist.service.js";
import { getTemplates, createTemplate, deleteTemplate } from "./template.service.js";
import { applyTemplate } from "./applyTemplate.service.js";
import { sendFriendRequest, receiveFriendRequest } from "./friend.service.js";
import { getCart, upsertCart, deleteCart } from "./cart.service.js";
import { getAllFinance, getFinanceById, createFinance, updateFinance, deleteFinance, settleDebt, getSummary } from "./finance.service.js";
import { getAllBudgets, getBudgetById, createBudget, updateBudget, deleteBudget } from "./budget.service.js";
import { getAllVendors, getVendorById, createVendor, updateVendor, deleteVendor } from "./vendor.service.js";
import { getAllCustomers, getCustomerById, createCustomer, updateCustomer, deleteCustomer } from "./customer.service.js";
import { getAllPurchaseOrders, getPurchaseOrderById, createPurchaseOrder, updatePurchaseOrder, deletePurchaseOrder } from "./purchaseOrder.service.js";
import { getAllSalesOrders, getSalesOrderById, createSalesOrder, updateSalesOrder, deleteSalesOrder } from "./salesOrder.service.js";

export const authService = { register, login, decodeSession };
export const userService = { getMe, updateUser };
export const groupService = { getAllGroups, getGroupById, createGroup, updateGroup, deleteGroup, setupPrimaryGroup };
export const categoryService = { getAllCategories, getCategoryById, createCategory, updateCategory, deleteCategory };
export const productService = { getAllProducts, getProductById, createProduct, updateProduct, deleteProduct, convertGroupPrices };
export const orderService = { getAllOrders, getOrderById, createOrder, updateOrder, deleteOrder };
export const inventoryService = { getAllInventory, getInventoryById, upsertInventory, updateInventory, deleteInventory };
export const wishlistService = { getAllWishlists, getWishlistById, createWishlist, updateWishlist, deleteWishlist };
export const templateService = { getTemplates, createTemplate, deleteTemplate };
export const applyTemplateService = { applyTemplate };
export const friendService = { sendFriendRequest, receiveFriendRequest };
export const cartService = { getCart, upsertCart, deleteCart };
export const financeService = { getAllFinance, getFinanceById, createFinance, updateFinance, deleteFinance, settleDebt, getSummary };
export const budgetService = { getAllBudgets, getBudgetById, createBudget, updateBudget, deleteBudget };
export const vendorService = { getAllVendors, getVendorById, createVendor, updateVendor, deleteVendor };
export const customerService = { getAllCustomers, getCustomerById, createCustomer, updateCustomer, deleteCustomer };
export const purchaseOrderService = { getAllPurchaseOrders, getPurchaseOrderById, createPurchaseOrder, updatePurchaseOrder, deletePurchaseOrder };
export const salesOrderService = { getAllSalesOrders, getSalesOrderById, createSalesOrder, updateSalesOrder, deleteSalesOrder };
