export const systemTemplates = [
    {
        name: "Basic Grocery",
        emoji: "🛒",
        description: "A starter template for everyday grocery shopping.",
        isSystem: true,
        categories: [
            { name: "Fruits & Vegetables", icon: "🥦", color: "#4CAF50" },
            { name: "Dairy", icon: "🥛", color: "#2196F3" },
            { name: "Bakery", icon: "🍞", color: "#FF9800" },
            { name: "Meat & Seafood", icon: "🥩", color: "#F44336" },
            { name: "Beverages", icon: "🧃", color: "#9C27B0" },
            { name: "Snacks", icon: "🍿", color: "#FF5722" },
            { name: "Cleaning", icon: "🧹", color: "#607D8B" },
        ],
        products: [
            { name: "Apples", category: "Fruits & Vegetables", price: "2.99", unit: "kg" },
            { name: "Bananas", category: "Fruits & Vegetables", price: "1.49", unit: "bunch" },
            { name: "Spinach", category: "Fruits & Vegetables", price: "1.99", unit: "bag" },
            { name: "Milk", category: "Dairy", price: "3.49", unit: "liter" },
            { name: "Butter", category: "Dairy", price: "4.99", unit: "pack" },
            { name: "Cheddar Cheese", category: "Dairy", price: "5.99", unit: "pack" },
            { name: "Bread", category: "Bakery", price: "2.49", unit: "loaf" },
            { name: "Eggs", category: "Dairy", price: "3.99", unit: "dozen" },
            { name: "Chicken Breast", category: "Meat & Seafood", price: "7.99", unit: "kg" },
            { name: "Orange Juice", category: "Beverages", price: "3.99", unit: "liter" },
            { name: "Chips", category: "Snacks", price: "2.99", unit: "bag" },
            { name: "Dish Soap", category: "Cleaning", price: "2.49", unit: "bottle" },
        ],
    },
    {
        name: "Meal Prep",
        emoji: "🍱",
        description: "Optimized for weekly meal prepping.",
        isSystem: true,
        categories: [
            { name: "Proteins", icon: "🥩", color: "#F44336" },
            { name: "Grains", icon: "🌾", color: "#FF9800" },
            { name: "Vegetables", icon: "🥦", color: "#4CAF50" },
            { name: "Sauces & Spices", icon: "🧂", color: "#795548" },
            { name: "Oils & Fats", icon: "🫙", color: "#FFC107" },
        ],
        products: [
            { name: "Chicken Thighs", category: "Proteins", price: "6.99", unit: "kg" },
            { name: "Ground Turkey", category: "Proteins", price: "7.49", unit: "kg" },
            { name: "Salmon Fillet", category: "Proteins", price: "12.99", unit: "kg" },
            { name: "Brown Rice", category: "Grains", price: "3.49", unit: "kg" },
            { name: "Quinoa", category: "Grains", price: "5.99", unit: "kg" },
            { name: "Oats", category: "Grains", price: "2.99", unit: "kg" },
            { name: "Broccoli", category: "Vegetables", price: "1.99", unit: "head" },
            { name: "Sweet Potato", category: "Vegetables", price: "2.49", unit: "kg" },
            { name: "Bell Peppers", category: "Vegetables", price: "3.49", unit: "pack" },
            { name: "Olive Oil", category: "Oils & Fats", price: "8.99", unit: "bottle" },
            { name: "Soy Sauce", category: "Sauces & Spices", price: "2.99", unit: "bottle" },
            { name: "Garlic Powder", category: "Sauces & Spices", price: "1.99", unit: "jar" },
        ],
    },
];
