export const systemTemplates = [
    // ── Personal ──────────────────────────────────────────────────────────────
    {
        name: "Basic Grocery",
        emoji: "🛒",
        description: "A starter template for everyday grocery shopping.",
        isSystem: true,
        type: "personal",
        categories: [
            { name: "Fruits & Vegetables", icon: "🥦", color: "#4CAF50" },
            { name: "Dairy", icon: "🥛", color: "#2196F3" },
            { name: "Bakery", icon: "🍞", color: "#FF9800" },
            { name: "Meat & Seafood", icon: "🥩", color: "#F44336" },
            { name: "Beverages", icon: "🧃", color: "#9C27B0" },
            { name: "Snacks", icon: "🍿", color: "#FF5722" },
            { name: "Cleaning", icon: "🧹", color: "#607D8B" },
        ],
        products: [
            { name: "Apples", category: "Fruits & Vegetables", price: "2.99", unit: "kg" },
            { name: "Bananas", category: "Fruits & Vegetables", price: "1.49", unit: "bunch" },
            { name: "Spinach", category: "Fruits & Vegetables", price: "1.99", unit: "bag" },
            { name: "Milk", category: "Dairy", price: "3.49", unit: "ltr" },
            { name: "Butter", category: "Dairy", price: "4.99", unit: "pack" },
            { name: "Cheddar Cheese", category: "Dairy", price: "5.99", unit: "pack" },
            { name: "Bread", category: "Bakery", price: "2.49", unit: "loaf" },
            { name: "Eggs", category: "Dairy", price: "3.99", unit: "dozen" },
            { name: "Chicken Breast", category: "Meat & Seafood", price: "7.99", unit: "kg" },
            { name: "Orange Juice", category: "Beverages", price: "3.99", unit: "ltr" },
            { name: "Chips", category: "Snacks", price: "2.99", unit: "bag" },
            { name: "Dish Soap", category: "Cleaning", price: "2.49", unit: "bottle" },
        ],
    },
    {
        name: "Meal Prep",
        emoji: "🍱",
        description: "Optimised for weekly meal prepping.",
        isSystem: true,
        type: "personal",
        categories: [
            { name: "Proteins", icon: "🥩", color: "#F44336" },
            { name: "Grains", icon: "🌾", color: "#FF9800" },
            { name: "Vegetables", icon: "🥦", color: "#4CAF50" },
            { name: "Sauces & Spices", icon: "🧂", color: "#795548" },
            { name: "Oils & Fats", icon: "🫙", color: "#FFC107" },
        ],
        products: [
            { name: "Chicken Thighs", category: "Proteins", price: "6.99", unit: "kg" },
            { name: "Ground Turkey", category: "Proteins", price: "7.49", unit: "kg" },
            { name: "Salmon Fillet", category: "Proteins", price: "12.99", unit: "kg" },
            { name: "Brown Rice", category: "Grains", price: "3.49", unit: "kg" },
            { name: "Quinoa", category: "Grains", price: "5.99", unit: "kg" },
            { name: "Oats", category: "Grains", price: "2.99", unit: "kg" },
            { name: "Broccoli", category: "Vegetables", price: "1.99", unit: "head" },
            { name: "Sweet Potato", category: "Vegetables", price: "2.49", unit: "kg" },
            { name: "Bell Peppers", category: "Vegetables", price: "3.49", unit: "pack" },
            { name: "Olive Oil", category: "Oils & Fats", price: "8.99", unit: "bottle" },
            { name: "Soy Sauce", category: "Sauces & Spices", price: "2.99", unit: "bottle" },
            { name: "Garlic Powder", category: "Sauces & Spices", price: "1.99", unit: "jar" },
        ],
    },
    {
        name: "Home & Household",
        emoji: "🏠",
        description: "Everything you need to run a home smoothly.",
        isSystem: true,
        type: "personal",
        categories: [
            { name: "Cleaning Supplies", icon: "🧹", color: "#607D8B" },
            { name: "Toiletries", icon: "🧴", color: "#E91E63" },
            { name: "Kitchen", icon: "🍳", color: "#FF9800" },
            { name: "Laundry", icon: "👕", color: "#2196F3" },
            { name: "Electronics", icon: "🔌", color: "#9C27B0" },
        ],
        products: [
            { name: "Shampoo", category: "Toiletries", price: "5.99", unit: "bottle" },
            { name: "Toothpaste", category: "Toiletries", price: "2.99", unit: "tube" },
            { name: "Toilet Paper", category: "Toiletries", price: "8.99", unit: "pack" },
            { name: "Detergent", category: "Laundry", price: "12.99", unit: "box" },
            { name: "Fabric Softener", category: "Laundry", price: "6.99", unit: "bottle" },
            { name: "Dishwasher Pods", category: "Kitchen", price: "9.99", unit: "pack" },
            { name: "Trash Bags", category: "Cleaning Supplies", price: "4.99", unit: "roll" },
            { name: "All-Purpose Cleaner", category: "Cleaning Supplies", price: "3.99", unit: "bottle" },
            { name: "Light Bulbs", category: "Electronics", price: "7.99", unit: "pack" },
        ],
    },

    // ── Business ──────────────────────────────────────────────────────────────
    {
        name: "Retail Shop",
        emoji: "🏪",
        description: "Complete inventory and product catalogue for a retail store covering electronics, clothing, accessories, and operations.",
        isSystem: true,
        type: "business",
        categories: [
            {
                name: "Electronics",
                description: "Consumer electronics, gadgets, and tech accessories sold on the shop floor.",
                icon: "📱",
                color: "#2196F3",
            },
            {
                name: "Clothing",
                description: "Apparel and garments for men, women, and children across all seasons.",
                icon: "👗",
                color: "#E91E63",
            },
            {
                name: "Footwear",
                description: "Shoes, sandals, and sports footwear for all age groups.",
                icon: "👟",
                color: "#9C27B0",
            },
            {
                name: "Accessories",
                description: "Jewellery, bags, belts, watches, and fashion add-ons.",
                icon: "💍",
                color: "#FF9800",
            },
            {
                name: "Packaging & Supplies",
                description: "Carry bags, boxes, tape, and wrapping materials used for dispatch and billing.",
                icon: "📦",
                color: "#795548",
            },
            {
                name: "Stationery & Billing",
                description: "POS consumables, receipt rolls, price tags, and office stationery.",
                icon: "📝",
                color: "#607D8B",
            },
            {
                name: "Toys & Games",
                description: "Board games, action figures, puzzles, and children's toys.",
                icon: "🎮",
                color: "#FF5722",
            },
            {
                name: "Home & Decor",
                description: "Decorative items, photo frames, candles, and small home furnishings.",
                icon: "🏡",
                color: "#4CAF50",
            },
        ],
        products: [
            // Electronics
            { name: "Bluetooth Earbuds", category: "Electronics", price: "1299", unit: "pcs", description: "True wireless in-ear earbuds with 20 hr battery life" },
            { name: "USB-C Charging Cable (1m)", category: "Electronics", price: "199", unit: "pcs", description: "Fast-charge braided USB-C cable" },
            { name: "Screen Protector (6.5\")", category: "Electronics", price: "99", unit: "pcs", description: "Tempered glass screen protector for large-screen phones" },
            { name: "Phone Case (Universal)", category: "Electronics", price: "149", unit: "pcs", description: "Silicone drop-proof phone case" },
            { name: "Power Bank 10000 mAh", category: "Electronics", price: "899", unit: "pcs", description: "Dual-port portable power bank" },
            { name: "Smart Watch (Basic)", category: "Electronics", price: "2499", unit: "pcs", description: "Fitness tracker with heart-rate monitor and notifications" },
            { name: "Wireless Charger Pad", category: "Electronics", price: "599", unit: "pcs", description: "10W Qi-certified wireless charging pad" },
            // Clothing
            { name: "Men's Cotton T-Shirt", category: "Clothing", price: "349", unit: "pcs", description: "Round-neck 100% cotton tee — S/M/L/XL" },
            { name: "Women's Kurti", category: "Clothing", price: "549", unit: "pcs", description: "Printed cotton kurti — XS to 3XL" },
            { name: "Denim Jeans (Unisex)", category: "Clothing", price: "1299", unit: "pcs", description: "Slim-fit stretch denim jeans" },
            { name: "Men's Formal Shirt", category: "Clothing", price: "799", unit: "pcs", description: "Cotton-blend full-sleeve formal shirt" },
            { name: "Women's Leggings", category: "Clothing", price: "299", unit: "pcs", description: "High-waist cotton-spandex leggings" },
            { name: "Kids' T-Shirt (3–12 yr)", category: "Clothing", price: "199", unit: "pcs", description: "Soft cotton crew-neck kids tee" },
            { name: "Track Pants", category: "Clothing", price: "449", unit: "pcs", description: "Unisex moisture-wicking track pants" },
            // Footwear
            { name: "Men's Casual Sneakers", category: "Footwear", price: "1499", unit: "pair", description: "Canvas lace-up sneakers — sizes 6–12" },
            { name: "Women's Block Heels", category: "Footwear", price: "999", unit: "pair", description: "3-inch block-heel sandal — sizes 4–9" },
            { name: "Kids' School Shoes", category: "Footwear", price: "699", unit: "pair", description: "Black leather-look school shoes — sizes 1–8" },
            { name: "Sports Running Shoes", category: "Footwear", price: "1999", unit: "pair", description: "Lightweight mesh running shoes with EVA sole" },
            { name: "Flip Flops", category: "Footwear", price: "199", unit: "pair", description: "EVA rubber flip flops — all sizes" },
            // Accessories
            { name: "Tote Bag", category: "Accessories", price: "399", unit: "pcs", description: "Canvas tote bag with zipper pocket" },
            { name: "Leather Wallet (Men's)", category: "Accessories", price: "599", unit: "pcs", description: "Bi-fold PU leather wallet with card slots" },
            { name: "Sunglasses (UV400)", category: "Accessories", price: "299", unit: "pcs", description: "Polarised UV400 sunglasses" },
            { name: "Fashion Wristwatch", category: "Accessories", price: "1299", unit: "pcs", description: "Analog quartz wristwatch — stainless steel strap" },
            { name: "Beaded Bracelet Set", category: "Accessories", price: "149", unit: "set", description: "6-piece elastic beaded bracelet set" },
            { name: "Leather Belt", category: "Accessories", price: "349", unit: "pcs", description: "PU leather reversible belt — sizes 28\"–42\"" },
            // Packaging
            { name: "Carry Bags (Small)", category: "Packaging & Supplies", price: "0.50", unit: "pcs", description: "HDPE carry bags 8×10 inch" },
            { name: "Carry Bags (Large)", category: "Packaging & Supplies", price: "1.00", unit: "pcs", description: "HDPE carry bags 12×16 inch" },
            { name: "Bubble Wrap Roll", category: "Packaging & Supplies", price: "349", unit: "roll", description: "300m small-bubble wrap roll" },
            { name: "Kraft Paper Box (Medium)", category: "Packaging & Supplies", price: "12", unit: "pcs", description: "Corrugated kraft box 10×8×4 inch" },
            { name: "Packing Tape", category: "Packaging & Supplies", price: "49", unit: "roll", description: "48mm × 100m brown packing tape" },
            // Stationery & Billing
            { name: "Thermal Receipt Roll (80mm)", category: "Stationery & Billing", price: "15", unit: "roll", description: "80mm × 80m thermal POS paper roll" },
            { name: "Price Tag Labels", category: "Stationery & Billing", price: "49", unit: "pack", description: "500-pcs self-adhesive price tag stickers" },
            { name: "Ballpoint Pens", category: "Stationery & Billing", price: "15", unit: "pack", description: "10-pc blue ballpoint pen pack" },
            { name: "A4 Paper (500 sheets)", category: "Stationery & Billing", price: "299", unit: "ream", description: "75 GSM A4 copier paper" },
            { name: "Stapler", category: "Stationery & Billing", price: "199", unit: "pcs", description: "Full-strip 26/6 stapler with staples" },
            // Toys & Games
            { name: "Wooden Building Blocks", category: "Toys & Games", price: "499", unit: "set", description: "50-pc natural wooden block set for ages 2+" },
            { name: "Board Game (Family)", category: "Toys & Games", price: "799", unit: "pcs", description: "Classic family board game for 2–6 players" },
            { name: "Remote Control Car", category: "Toys & Games", price: "1299", unit: "pcs", description: "1:16 scale RC car with rechargeable battery" },
            { name: "Jigsaw Puzzle (500 pcs)", category: "Toys & Games", price: "399", unit: "pcs", description: "500-piece landscape jigsaw puzzle" },
            // Home & Decor
            { name: "Photo Frame (5×7)", category: "Home & Decor", price: "199", unit: "pcs", description: "Wooden tabletop photo frame 5×7 inch" },
            { name: "Scented Candle", category: "Home & Decor", price: "299", unit: "pcs", description: "Soy wax aromatherapy candle — 40 hr burn" },
            { name: "Decorative Cushion Cover", category: "Home & Decor", price: "199", unit: "pcs", description: "16×16 inch printed cotton cushion cover" },
            { name: "Wall Clock", category: "Home & Decor", price: "599", unit: "pcs", description: "12-inch silent sweep quartz wall clock" },
        ],
    },

    {
        name: "Restaurant / Café",
        emoji: "☕",
        description: "Complete ingredient and supply catalogue for a restaurant, café, or cloud kitchen.",
        isSystem: true,
        type: "business",
        categories: [
            {
                name: "Produce",
                description: "Fresh fruits and vegetables sourced daily for cooking and garnishing.",
                icon: "🥦",
                color: "#4CAF50",
            },
            {
                name: "Meat & Fish",
                description: "Fresh and frozen proteins including poultry, red meat, and seafood.",
                icon: "🥩",
                color: "#F44336",
            },
            {
                name: "Dairy & Eggs",
                description: "Milk, cream, butter, cheese, and fresh eggs used in cooking and baking.",
                icon: "🥛",
                color: "#2196F3",
            },
            {
                name: "Dry Goods & Grains",
                description: "Flour, rice, lentils, sugar, salt, and other pantry staples with long shelf life.",
                icon: "🌾",
                color: "#FF9800",
            },
            {
                name: "Oils, Sauces & Condiments",
                description: "Cooking oils, vinegars, soy sauce, ketchup, hot sauce, and marinades.",
                icon: "🫙",
                color: "#795548",
            },
            {
                name: "Spices & Herbs",
                description: "Whole and ground spices, dried herbs, and spice blends for seasoning.",
                icon: "🧂",
                color: "#8BC34A",
            },
            {
                name: "Beverages & Coffee",
                description: "Coffee beans, tea, syrups, juices, and soft drinks served to customers.",
                icon: "☕",
                color: "#5D4037",
            },
            {
                name: "Bakery Ingredients",
                description: "Yeast, baking powder, cocoa, vanilla, and other baking essentials.",
                icon: "🍞",
                color: "#FF7043",
            },
            {
                name: "Frozen & Chilled",
                description: "Frozen vegetables, ice cream, frozen meats, and chilled ready-to-use items.",
                icon: "🧊",
                color: "#00BCD4",
            },
            {
                name: "Disposables & Packaging",
                description: "Cups, containers, straws, napkins, takeaway boxes, and food-grade packaging.",
                icon: "🥡",
                color: "#607D8B",
            },
            {
                name: "Cleaning & Hygiene",
                description: "Kitchen degreasers, sanitisers, gloves, and dishwashing supplies.",
                icon: "🧼",
                color: "#9E9E9E",
            },
        ],
        products: [
            // Produce
            { name: "Tomatoes", category: "Produce", price: "40", unit: "kg", description: "Fresh red tomatoes" },
            { name: "Onions", category: "Produce", price: "30", unit: "kg", description: "Red and white onions" },
            { name: "Garlic", category: "Produce", price: "80", unit: "kg", description: "Fresh garlic bulbs" },
            { name: "Ginger", category: "Produce", price: "100", unit: "kg", description: "Fresh ginger root" },
            { name: "Coriander Leaves", category: "Produce", price: "20", unit: "bunch", description: "Fresh coriander for garnishing" },
            { name: "Lemon", category: "Produce", price: "60", unit: "kg", description: "Fresh lemons" },
            { name: "Potatoes", category: "Produce", price: "25", unit: "kg", description: "Fresh potatoes" },
            { name: "Capsicum (Mixed)", category: "Produce", price: "80", unit: "kg", description: "Red, yellow, green capsicums" },
            { name: "Spinach", category: "Produce", price: "30", unit: "bundle", description: "Fresh palak / spinach" },
            { name: "Mushrooms (Button)", category: "Produce", price: "120", unit: "kg", description: "Fresh button mushrooms" },
            // Meat & Fish
            { name: "Chicken Breast (Boneless)", category: "Meat & Fish", price: "280", unit: "kg", description: "Skinless boneless chicken breast" },
            { name: "Chicken Whole (Curry Cut)", category: "Meat & Fish", price: "200", unit: "kg", description: "Curry-cut whole chicken" },
            { name: "Mutton (Bone-in)", category: "Meat & Fish", price: "750", unit: "kg", description: "Fresh bone-in mutton pieces" },
            { name: "Prawns (Medium)", category: "Meat & Fish", price: "550", unit: "kg", description: "Cleaned and deveined medium prawns" },
            { name: "Fish Fillet (Basa)", category: "Meat & Fish", price: "350", unit: "kg", description: "Fresh basa fish fillets" },
            { name: "Eggs (Tray)", category: "Dairy & Eggs", price: "350", unit: "tray", description: "30-egg tray — farm fresh" },
            // Dairy & Eggs
            { name: "Full-Fat Milk", category: "Dairy & Eggs", price: "60", unit: "ltr", description: "Fresh full-cream milk" },
            { name: "Fresh Cream (25%)", category: "Dairy & Eggs", price: "180", unit: "ltr", description: "25% fat fresh cream for cooking and desserts" },
            { name: "Butter (Unsalted)", category: "Dairy & Eggs", price: "550", unit: "kg", description: "Unsalted white butter" },
            { name: "Paneer", category: "Dairy & Eggs", price: "380", unit: "kg", description: "Fresh cottage cheese" },
            { name: "Cheddar Cheese (Block)", category: "Dairy & Eggs", price: "700", unit: "kg", description: "Processed cheddar cheese block" },
            { name: "Mozzarella (Shredded)", category: "Dairy & Eggs", price: "900", unit: "kg", description: "Low-moisture shredded mozzarella" },
            { name: "Curd / Yoghurt", category: "Dairy & Eggs", price: "60", unit: "kg", description: "Set curd for marinades and sides" },
            // Dry Goods & Grains
            { name: "Basmati Rice", category: "Dry Goods & Grains", price: "90", unit: "kg", description: "Long-grain aged basmati rice" },
            { name: "All-Purpose Flour (Maida)", category: "Dry Goods & Grains", price: "40", unit: "kg", description: "Refined wheat flour" },
            { name: "Whole Wheat Flour (Atta)", category: "Dry Goods & Grains", price: "45", unit: "kg", description: "Stone-ground whole wheat atta" },
            { name: "Sugar (Fine)", category: "Dry Goods & Grains", price: "45", unit: "kg", description: "Refined white granulated sugar" },
            { name: "Salt (Iodised)", category: "Dry Goods & Grains", price: "20", unit: "kg", description: "Iodised table salt" },
            { name: "Chana Dal", category: "Dry Goods & Grains", price: "80", unit: "kg", description: "Split Bengal gram" },
            { name: "Toor Dal", category: "Dry Goods & Grains", price: "130", unit: "kg", description: "Split pigeon peas" },
            // Oils, Sauces & Condiments
            { name: "Refined Sunflower Oil", category: "Oils, Sauces & Condiments", price: "150", unit: "ltr", description: "Refined sunflower cooking oil" },
            { name: "Extra Virgin Olive Oil", category: "Oils, Sauces & Condiments", price: "650", unit: "ltr", description: "Cold-pressed extra virgin olive oil" },
            { name: "Soy Sauce (Dark)", category: "Oils, Sauces & Condiments", price: "180", unit: "bottle", description: "Dark soy sauce for stir-fries and gravies" },
            { name: "Tomato Ketchup (Bulk)", category: "Oils, Sauces & Condiments", price: "220", unit: "kg", description: "1 kg squeeze-pack tomato ketchup" },
            { name: "White Vinegar", category: "Oils, Sauces & Condiments", price: "60", unit: "ltr", description: "Distilled white vinegar" },
            { name: "Mayonnaise", category: "Oils, Sauces & Condiments", price: "300", unit: "kg", description: "Eggless / regular mayo — 1 kg jar" },
            // Spices & Herbs
            { name: "Turmeric Powder", category: "Spices & Herbs", price: "180", unit: "kg", description: "Pure haldi powder" },
            { name: "Red Chilli Powder", category: "Spices & Herbs", price: "220", unit: "kg", description: "Kashmiri / hot red chilli powder" },
            { name: "Cumin Seeds", category: "Spices & Herbs", price: "300", unit: "kg", description: "Whole jeera for tempering" },
            { name: "Coriander Powder", category: "Spices & Herbs", price: "160", unit: "kg", description: "Ground dhania powder" },
            { name: "Garam Masala", category: "Spices & Herbs", price: "350", unit: "kg", description: "Blended whole spice powder" },
            { name: "Black Pepper (Whole)", category: "Spices & Herbs", price: "500", unit: "kg", description: "Whole black peppercorns" },
            { name: "Bay Leaves", category: "Spices & Herbs", price: "200", unit: "kg", description: "Dried tej patta leaves" },
            // Beverages & Coffee
            { name: "Arabica Coffee Beans", category: "Beverages & Coffee", price: "800", unit: "kg", description: "Single-origin medium-roast arabica" },
            { name: "Earl Grey Tea Bags", category: "Beverages & Coffee", price: "350", unit: "box", description: "100-bag Earl Grey tea box" },
            { name: "Sugar Syrup (1 ltr)", category: "Beverages & Coffee", price: "120", unit: "bottle", description: "Simple 1:1 sugar syrup for cocktails and coffee" },
            { name: "Packaged Mineral Water (500ml)", category: "Beverages & Coffee", price: "20", unit: "pcs", description: "Sealed 500 ml drinking water bottle" },
            { name: "Mango Pulp (Can)", category: "Beverages & Coffee", price: "180", unit: "can", description: "Alphonso mango pulp — 850g can" },
            // Bakery Ingredients
            { name: "Instant Dry Yeast", category: "Bakery Ingredients", price: "180", unit: "kg", description: "Instant active dry yeast for breads" },
            { name: "Baking Powder", category: "Bakery Ingredients", price: "120", unit: "kg", description: "Double-acting baking powder" },
            { name: "Cocoa Powder (Unsweetened)", category: "Bakery Ingredients", price: "450", unit: "kg", description: "Dark Dutch-process cocoa powder" },
            { name: "Vanilla Extract", category: "Bakery Ingredients", price: "500", unit: "ltr", description: "Pure vanilla extract" },
            { name: "Dark Chocolate (Compound)", category: "Bakery Ingredients", price: "350", unit: "kg", description: "55% dark compound chocolate callets" },
            // Frozen & Chilled
            { name: "Frozen Sweet Corn", category: "Frozen & Chilled", price: "120", unit: "kg", description: "IQF sweet corn kernels" },
            { name: "Frozen French Fries", category: "Frozen & Chilled", price: "180", unit: "kg", description: "9mm straight-cut fries" },
            { name: "Vanilla Ice Cream (Bulk)", category: "Frozen & Chilled", price: "400", unit: "ltr", description: "4-litre bulk vanilla ice cream tub" },
            // Disposables & Packaging
            { name: "Disposable Cups (250ml)", category: "Disposables & Packaging", price: "180", unit: "pack", description: "100-pc single-wall paper cups" },
            { name: "Takeaway Containers (500ml)", category: "Disposables & Packaging", price: "250", unit: "pack", description: "50-pc microwavable PP containers with lids" },
            { name: "Kraft Paper Bags", category: "Disposables & Packaging", price: "300", unit: "pack", description: "100-pc brown kraft carry bags" },
            { name: "Drinking Straws (Paper)", category: "Disposables & Packaging", price: "120", unit: "pack", description: "200-pc biodegradable paper straws" },
            { name: "Tissue Napkins", category: "Disposables & Packaging", price: "80", unit: "pack", description: "100-pc 2-ply dinner napkins" },
            { name: "Aluminium Foil Roll", category: "Disposables & Packaging", price: "150", unit: "roll", description: "45m × 30cm heavy-duty foil roll" },
            // Cleaning & Hygiene
            { name: "Kitchen Degreaser Spray", category: "Cleaning & Hygiene", price: "220", unit: "bottle", description: "1-litre commercial kitchen degreaser" },
            { name: "Dishwash Liquid (5 ltr)", category: "Cleaning & Hygiene", price: "350", unit: "can", description: "5-litre concentrated dishwashing liquid" },
            { name: "Latex Gloves (M)", category: "Cleaning & Hygiene", price: "180", unit: "box", description: "100-pc food-safe latex gloves — medium" },
            { name: "Hand Sanitiser (500ml)", category: "Cleaning & Hygiene", price: "120", unit: "bottle", description: "70% alcohol hand sanitiser" },
            { name: "Scrub Pad", category: "Cleaning & Hygiene", price: "30", unit: "pcs", description: "Heavy-duty non-scratch scrubbing pad" },
        ],
    },

    {
        name: "Office Supplies",
        emoji: "🖥️",
        description: "Full catalogue of stationery, tech, pantry, and facilities supplies for a modern office.",
        isSystem: true,
        type: "business",
        categories: [
            {
                name: "Stationery",
                description: "Paper, pens, notebooks, folders, and everyday desk consumables.",
                icon: "✏️",
                color: "#607D8B",
            },
            {
                name: "Printing & Imaging",
                description: "Printer cartridges, toner, photo paper, and scanning supplies.",
                icon: "🖨️",
                color: "#455A64",
            },
            {
                name: "Tech & Peripherals",
                description: "Monitors, keyboards, mice, cables, hubs, and IT accessories.",
                icon: "💻",
                color: "#2196F3",
            },
            {
                name: "Networking",
                description: "Routers, switches, patch cables, and Wi-Fi extenders.",
                icon: "📡",
                color: "#3F51B5",
            },
            {
                name: "Furniture & Ergonomics",
                description: "Chairs, desks, monitor stands, footrests, and ergonomic accessories.",
                icon: "🪑",
                color: "#795548",
            },
            {
                name: "Pantry & Beverages",
                description: "Coffee, tea, snacks, and pantry essentials for the office kitchen.",
                icon: "☕",
                color: "#FF9800",
            },
            {
                name: "Cleaning & Facilities",
                description: "Sanitisers, wipes, trash bags, and general facility maintenance supplies.",
                icon: "🧹",
                color: "#4CAF50",
            },
            {
                name: "Presentation & AV",
                description: "Whiteboards, markers, flip charts, HDMI adapters, and projector accessories.",
                icon: "📊",
                color: "#9C27B0",
            },
            {
                name: "Packaging & Dispatch",
                description: "Courier bags, bubble wrap, tape guns, and dispatch materials.",
                icon: "📦",
                color: "#FF5722",
            },
        ],
        products: [
            // Stationery
            { name: "A4 Paper (500 sheets)", category: "Stationery", price: "299", unit: "ream", description: "75 GSM A4 copier paper" },
            { name: "Ballpoint Pens (Blue, 10pc)", category: "Stationery", price: "50", unit: "pack", description: "Reynolds/Cello 10-pc blue pen pack" },
            { name: "Sticky Notes (3×3, 5-pad)", category: "Stationery", price: "99", unit: "pack", description: "5 × 100-sheet neon sticky note pack" },
            { name: "Spiral Notebook (A5)", category: "Stationery", price: "79", unit: "pcs", description: "100-page ruled A5 spiral notebook" },
            { name: "Highlighters (5 colours)", category: "Stationery", price: "89", unit: "set", description: "Chisel-tip fluorescent highlighter set" },
            { name: "Permanent Marker (Black)", category: "Stationery", price: "30", unit: "pcs", description: "Broad-tip permanent marker" },
            { name: "Scissors", category: "Stationery", price: "49", unit: "pcs", description: "7-inch stainless steel scissors" },
            { name: "Stapler (Full Strip)", category: "Stationery", price: "199", unit: "pcs", description: "26/6 full-strip stapler" },
            { name: "Stapler Pins (1000pc)", category: "Stationery", price: "30", unit: "box", description: "26/6 staple pins — 1000 count" },
            { name: "Transparent Tape (6-roll)", category: "Stationery", price: "79", unit: "pack", description: "18mm × 66m OPP tape — 6-roll pack" },
            { name: "Paper Clips (100pc)", category: "Stationery", price: "25", unit: "box", description: "28mm silver paper clips" },
            { name: "File Folders (A4)", category: "Stationery", price: "15", unit: "pcs", description: "L-shaped polypropylene file folder" },
            { name: "Lever Arch File", category: "Stationery", price: "129", unit: "pcs", description: "A4 lever arch binder — 7 cm spine" },
            { name: "Rubber Bands (100g)", category: "Stationery", price: "35", unit: "pack", description: "Mixed-size rubber band pack" },
            // Printing & Imaging
            { name: "Black Ink Cartridge (HP 678)", category: "Printing & Imaging", price: "499", unit: "pcs", description: "HP 678 black ink cartridge — ~480 pages" },
            { name: "Colour Ink Cartridge (HP 678)", category: "Printing & Imaging", price: "599", unit: "pcs", description: "HP 678 tri-colour ink cartridge" },
            { name: "Laser Toner (Black)", category: "Printing & Imaging", price: "1800", unit: "pcs", description: "Generic black toner for laser printers" },
            { name: "Photo Paper (Glossy, A4)", category: "Printing & Imaging", price: "299", unit: "pack", description: "20-sheet 200 GSM glossy photo paper" },
            { name: "Laminating Pouches (A4, 100pc)", category: "Printing & Imaging", price: "350", unit: "pack", description: "80 micron A4 laminating pouches" },
            // Tech & Peripherals
            { name: "USB-A to USB-C Cable", category: "Tech & Peripherals", price: "199", unit: "pcs", description: "1m braided fast-charge cable" },
            { name: "HDMI Cable (2m)", category: "Tech & Peripherals", price: "299", unit: "pcs", description: "4K HDMI 2.0 cable" },
            { name: "USB 3.0 Hub (4-port)", category: "Tech & Peripherals", price: "699", unit: "pcs", description: "4-port USB 3.0 hub with LED indicator" },
            { name: "Wireless Mouse", category: "Tech & Peripherals", price: "499", unit: "pcs", description: "2.4GHz wireless optical mouse" },
            { name: "Mechanical Keyboard", category: "Tech & Peripherals", price: "1999", unit: "pcs", description: "TKL mechanical keyboard — blue switches" },
            { name: "Laptop Stand (Aluminium)", category: "Tech & Peripherals", price: "1299", unit: "pcs", description: "Adjustable aluminium laptop riser" },
            { name: "Webcam (1080p)", category: "Tech & Peripherals", price: "1999", unit: "pcs", description: "Full-HD USB webcam with built-in mic" },
            { name: "External Hard Drive (1TB)", category: "Tech & Peripherals", price: "3499", unit: "pcs", description: "USB 3.0 portable 1TB HDD" },
            // Networking
            { name: "Cat6 Patch Cable (2m)", category: "Networking", price: "99", unit: "pcs", description: "RJ45 Cat6 ethernet patch cable" },
            { name: "Wi-Fi Router (Dual Band)", category: "Networking", price: "2499", unit: "pcs", description: "AC1200 dual-band Wi-Fi router" },
            { name: "8-Port Network Switch", category: "Networking", price: "1499", unit: "pcs", description: "Unmanaged Gigabit 8-port switch" },
            // Furniture & Ergonomics
            { name: "Ergonomic Office Chair", category: "Furniture & Ergonomics", price: "8999", unit: "pcs", description: "Mesh-back lumbar-support task chair" },
            { name: "Height-Adjustable Desk", category: "Furniture & Ergonomics", price: "15999", unit: "pcs", description: "Electric sit-stand desk 120×60cm" },
            { name: "Monitor Arm (Single)", category: "Furniture & Ergonomics", price: "2499", unit: "pcs", description: "VESA 75/100 single monitor arm" },
            { name: "Wrist Rest (Keyboard)", category: "Furniture & Ergonomics", price: "399", unit: "pcs", description: "Memory foam keyboard wrist rest" },
            { name: "Cable Management Tray", category: "Furniture & Ergonomics", price: "699", unit: "pcs", description: "Under-desk cable tray with brackets" },
            // Pantry & Beverages
            { name: "Instant Coffee (200g)", category: "Pantry & Beverages", price: "350", unit: "jar", description: "Nescafé Classic 200g jar" },
            { name: "Tea Bags (100pc)", category: "Pantry & Beverages", price: "180", unit: "box", description: "Tata Gold / Taj Mahal 100-bag box" },
            { name: "Sugar Sachets (200pc)", category: "Pantry & Beverages", price: "120", unit: "box", description: "5g white sugar sachets — 200-pack" },
            { name: "Biscuits / Cookies (Assorted)", category: "Pantry & Beverages", price: "150", unit: "pack", description: "Assorted office biscuit pack" },
            { name: "Mineral Water (500ml × 24)", category: "Pantry & Beverages", price: "280", unit: "carton", description: "Case of 24 × 500ml water bottles" },
            { name: "Paper Cups (100pc)", category: "Pantry & Beverages", price: "99", unit: "pack", description: "100-pc disposable paper cups for hot drinks" },
            // Cleaning & Facilities
            { name: "Hand Sanitiser (500ml)", category: "Cleaning & Facilities", price: "120", unit: "bottle", description: "70% IPA instant hand sanitiser" },
            { name: "Disinfectant Wipes (80pc)", category: "Cleaning & Facilities", price: "180", unit: "pack", description: "80-pc multi-surface disinfectant wipes" },
            { name: "Trash Bags (Large, 30pc)", category: "Cleaning & Facilities", price: "99", unit: "pack", description: "30 × 90L heavy-duty garbage bags" },
            { name: "Liquid Handwash (500ml)", category: "Cleaning & Facilities", price: "99", unit: "bottle", description: "Anti-bacterial foaming handwash" },
            { name: "Air Freshener Spray", category: "Cleaning & Facilities", price: "149", unit: "bottle", description: "300ml aerosol room freshener" },
            { name: "Toilet Paper Roll (12pc)", category: "Cleaning & Facilities", price: "199", unit: "pack", description: "2-ply 150-sheet toilet paper — 12-roll pack" },
            // Presentation & AV
            { name: "Whiteboard Markers (4 colours)", category: "Presentation & AV", price: "99", unit: "set", description: "4-colour dry-erase whiteboard markers" },
            { name: "Whiteboard Eraser", category: "Presentation & AV", price: "49", unit: "pcs", description: "Felt whiteboard duster" },
            { name: "HDMI-to-VGA Adapter", category: "Presentation & AV", price: "299", unit: "pcs", description: "Gold-plated HDMI male to VGA female adapter" },
            { name: "Wireless Presenter / Clicker", category: "Presentation & AV", price: "799", unit: "pcs", description: "2.4GHz laser presentation clicker" },
            { name: "Flip Chart Pad (A1)", category: "Presentation & AV", price: "499", unit: "pad", description: "50-sheet plain flip chart pad" },
            // Packaging & Dispatch
            { name: "Courier Bag (12×16)", category: "Packaging & Dispatch", price: "5", unit: "pcs", description: "POD tamper-evident poly courier bag" },
            { name: "Bubble Wrap (300m Roll)", category: "Packaging & Dispatch", price: "699", unit: "roll", description: "Small-bubble 300m wrap roll" },
            { name: "Packing Tape Gun", category: "Packaging & Dispatch", price: "199", unit: "pcs", description: "48mm tape dispenser gun" },
            { name: "Brown Packing Tape (48mm)", category: "Packaging & Dispatch", price: "49", unit: "roll", description: "48mm × 100m brown OPP tape" },
        ],
    },

    {
        name: "Freelancer / Agency",
        emoji: "💼",
        description: "Service catalogue and expense tracker for freelancers, consultants, and small digital agencies.",
        isSystem: true,
        type: "business",
        categories: [
            {
                name: "Design Services",
                description: "UI/UX design, graphic design, branding, and visual content creation services.",
                icon: "🎨",
                color: "#E91E63",
            },
            {
                name: "Development Services",
                description: "Web development, app development, API integration, and tech consulting.",
                icon: "💻",
                color: "#2196F3",
            },
            {
                name: "Marketing Services",
                description: "SEO, social media management, content writing, and paid advertising.",
                icon: "📣",
                color: "#FF9800",
            },
            {
                name: "Consulting & Strategy",
                description: "Business consulting, product strategy, audit, and advisory retainers.",
                icon: "📋",
                color: "#9C27B0",
            },
            {
                name: "Software Subscriptions",
                description: "SaaS tools, cloud hosting, domain registrations, and licensed software.",
                icon: "☁️",
                color: "#00BCD4",
            },
            {
                name: "Hardware & Equipment",
                description: "Laptops, cameras, microphones, and other physical tools of the trade.",
                icon: "🖥️",
                color: "#607D8B",
            },
            {
                name: "Office & Admin",
                description: "Stationery, notebooks, printer supplies, and co-working space costs.",
                icon: "📁",
                color: "#795548",
            },
            {
                name: "Travel & Client Meetings",
                description: "Cab fares, flight tickets, accommodation, and client entertainment.",
                icon: "✈️",
                color: "#4CAF50",
            },
        ],
        products: [
            // Design Services
            { name: "Logo Design", category: "Design Services", price: "8000", unit: "project", description: "Brand logo with 3 concepts, 2 revision rounds, source files" },
            { name: "Brand Identity Kit", category: "Design Services", price: "25000", unit: "project", description: "Logo, colour palette, typography, letterhead, brand guide" },
            { name: "UI Design (Mobile App)", category: "Design Services", price: "35000", unit: "project", description: "End-to-end UI screens for iOS/Android app — Figma delivery" },
            { name: "Web Page Design (per page)", category: "Design Services", price: "5000", unit: "pcs", description: "Single web page high-fidelity Figma design" },
            { name: "Social Media Post (per post)", category: "Design Services", price: "500", unit: "pcs", description: "Branded social media graphic — Instagram/LinkedIn format" },
            { name: "Social Media Pack (30 posts)", category: "Design Services", price: "12000", unit: "pack", description: "Monthly 30-post content design pack" },
            { name: "Pitch Deck Design", category: "Design Services", price: "15000", unit: "project", description: "10–15 slide investor / sales pitch deck design" },
            { name: "Banner / Poster Design", category: "Design Services", price: "1500", unit: "pcs", description: "Print-ready high-res banner or poster" },
            { name: "Video Editing (per minute)", category: "Design Services", price: "1000", unit: "min", description: "Professional video editing per finished minute" },
            // Development Services
            { name: "Website Development (5 pages)", category: "Development Services", price: "30000", unit: "project", description: "Responsive 5-page website — HTML/CSS/JS or WordPress" },
            { name: "E-Commerce Website", category: "Development Services", price: "60000", unit: "project", description: "Full e-commerce store with cart, payments, admin panel" },
            { name: "Mobile App (MVP)", category: "Development Services", price: "150000", unit: "project", description: "React Native MVP app for iOS & Android" },
            { name: "REST API Development", category: "Development Services", price: "40000", unit: "project", description: "Node.js/Python REST API with auth and documentation" },
            { name: "WordPress Customisation", category: "Development Services", price: "10000", unit: "project", description: "Theme/plugin customisation and deployment" },
            { name: "Bug Fixing (per hour)", category: "Development Services", price: "1500", unit: "hr", description: "Hourly rate for debugging and code fixes" },
            { name: "Code Review & Audit", category: "Development Services", price: "8000", unit: "project", description: "Security and quality code review with written report" },
            { name: "Tech Consulting (per hour)", category: "Development Services", price: "3000", unit: "hr", description: "CTO-level technology advisory — per hour" },
            // Marketing Services
            { name: "SEO Audit", category: "Marketing Services", price: "10000", unit: "project", description: "Full on-page and off-page SEO audit with action plan" },
            { name: "SEO Monthly Retainer", category: "Marketing Services", price: "20000", unit: "month", description: "On-page SEO, link building, and monthly ranking report" },
            { name: "Google Ads Management", category: "Marketing Services", price: "15000", unit: "month", description: "Google Search/Display campaign setup and management" },
            { name: "Meta Ads Management", category: "Marketing Services", price: "12000", unit: "month", description: "Facebook & Instagram paid campaign management" },
            { name: "Content Writing (per article)", category: "Marketing Services", price: "2000", unit: "pcs", description: "1000–1500 word SEO blog article" },
            { name: "Social Media Management", category: "Marketing Services", price: "18000", unit: "month", description: "3 platforms — content calendar, posting, and engagement" },
            { name: "Email Campaign (per campaign)", category: "Marketing Services", price: "5000", unit: "pcs", description: "Email copywriting, design, and Mailchimp/Klaviyo setup" },
            // Consulting & Strategy
            { name: "Business Strategy Session", category: "Consulting & Strategy", price: "5000", unit: "hr", description: "1-on-1 strategy consulting session — per hour" },
            { name: "Product Roadmap Workshop", category: "Consulting & Strategy", price: "25000", unit: "project", description: "Half-day facilitated product roadmap workshop" },
            { name: "Monthly Advisory Retainer", category: "Consulting & Strategy", price: "30000", unit: "month", description: "4 × 1-hour monthly advisory calls + async support" },
            { name: "Market Research Report", category: "Consulting & Strategy", price: "15000", unit: "project", description: "Competitor analysis and market sizing report" },
            { name: "Startup Pitch Coaching", category: "Consulting & Strategy", price: "12000", unit: "project", description: "Pitch narrative, deck review, and mock Q&A" },
            // Software Subscriptions
            { name: "Domain Registration (1 yr)", category: "Software Subscriptions", price: "999", unit: "year", description: ".com/.in domain — annual renewal" },
            { name: "Web Hosting (cPanel, 1 yr)", category: "Software Subscriptions", price: "3999", unit: "year", description: "Shared cPanel hosting — annual plan" },
            { name: "AWS / Cloud Hosting", category: "Software Subscriptions", price: "5000", unit: "month", description: "Monthly AWS/GCP/Azure cloud infrastructure cost" },
            { name: "Figma Professional", category: "Software Subscriptions", price: "1200", unit: "month", description: "Figma Professional plan — per editor seat" },
            { name: "Adobe Creative Cloud", category: "Software Subscriptions", price: "5499", unit: "month", description: "Adobe CC all-apps subscription" },
            { name: "Notion Team Plan", category: "Software Subscriptions", price: "800", unit: "month", description: "Notion Team workspace — per seat" },
            { name: "Zoom Pro", category: "Software Subscriptions", price: "1300", unit: "month", description: "Zoom Pro meeting plan" },
            { name: "GSuite / Google Workspace", category: "Software Subscriptions", price: "1250", unit: "month", description: "Google Workspace Business Starter — per user" },
            { name: "Slack Pro", category: "Software Subscriptions", price: "800", unit: "month", description: "Slack Pro plan — per user per month" },
            { name: "GitHub Team", category: "Software Subscriptions", price: "330", unit: "month", description: "GitHub Team plan — per user per month" },
            // Hardware & Equipment
            { name: "MacBook Pro 14\" (M3)", category: "Hardware & Equipment", price: "199000", unit: "pcs", description: "Apple MacBook Pro 14-inch M3 chip" },
            { name: "External SSD (1TB)", category: "Hardware & Equipment", price: "5999", unit: "pcs", description: "Samsung T7 / WD 1TB portable SSD" },
            { name: "USB-C Docking Station", category: "Hardware & Equipment", price: "6999", unit: "pcs", description: "7-in-1 USB-C hub with HDMI and PD" },
            { name: "27\" 4K Monitor", category: "Hardware & Equipment", price: "24999", unit: "pcs", description: "27-inch 4K IPS USB-C monitor" },
            { name: "Mirrorless Camera (APS-C)", category: "Hardware & Equipment", price: "55000", unit: "pcs", description: "APS-C mirrorless camera with kit lens" },
            { name: "USB Condenser Microphone", category: "Hardware & Equipment", price: "8999", unit: "pcs", description: "Cardioid USB condenser mic for podcasting/calls" },
            { name: "iPad + Apple Pencil", category: "Hardware & Equipment", price: "55000", unit: "set", description: "iPad 10th gen + 2nd gen Apple Pencil set" },
            { name: "Ring Light (18\")", category: "Hardware & Equipment", price: "3499", unit: "pcs", description: "18-inch dimmable LED ring light with stand" },
            // Office & Admin
            { name: "A4 Paper (500 sheets)", category: "Office & Admin", price: "299", unit: "ream", description: "75 GSM A4 copier paper" },
            { name: "Business Cards (500pc)", category: "Office & Admin", price: "999", unit: "pack", description: "Premium 400 GSM business cards — matte laminate" },
            { name: "Notebook (Hardbound, A5)", category: "Office & Admin", price: "299", unit: "pcs", description: "200-page ruled hardbound notebook" },
            { name: "Co-Working Day Pass", category: "Office & Admin", price: "500", unit: "day", description: "Hot-desk co-working space day pass" },
            { name: "Co-Working Monthly Desk", category: "Office & Admin", price: "8000", unit: "month", description: "Dedicated desk at co-working space" },
            { name: "Courier / Shipping", category: "Office & Admin", price: "80", unit: "shipment", description: "Domestic courier — per shipment up to 500g" },
            // Travel & Client Meetings
            { name: "Cab / Ride-share", category: "Travel & Client Meetings", price: "200", unit: "trip", description: "Ola/Uber cab for client meeting — per trip" },
            { name: "Flight Ticket (Domestic)", category: "Travel & Client Meetings", price: "5000", unit: "trip", description: "Economy domestic flight — per trip" },
            { name: "Hotel Accommodation", category: "Travel & Client Meetings", price: "3000", unit: "night", description: "Business hotel — per night" },
            { name: "Client Meal / Entertaining", category: "Travel & Client Meetings", price: "1500", unit: "pcs", description: "Client lunch or dinner expense" },
        ],
    },

    {
        name: "Grocery Store",
        emoji: "🥬",
        description: "Premium grocery and supermarket catalogue covering fresh produce, dairy, bakery, meat, beverages, and household essentials — built for quality-first grocery businesses.",
        isSystem: true,
        type: "business",
        categories: [
            {
                name: "Fresh Produce",
                description: "Seasonal fruits, vegetables, herbs, and salad greens — sourced fresh daily for quality-conscious customers.",
                icon: "🥦",
                color: "#4CAF50",
            },
            {
                name: "Dairy & Eggs",
                description: "Farm-fresh milk, artisan cheeses, butter, cream, yoghurt, and free-range eggs.",
                icon: "🥛",
                color: "#2196F3",
            },
            {
                name: "Meat & Seafood",
                description: "Fresh and chilled cuts of poultry, red meat, and cleaned seafood — halal and non-halal options.",
                icon: "🥩",
                color: "#F44336",
            },
            {
                name: "Bakery & Bread",
                description: "Fresh-baked artisan breads, buns, cakes, pastries, and cookies — baked in-store or sourced from local bakeries.",
                icon: "🍞",
                color: "#FF7043",
            },
            {
                name: "Pantry & Dry Goods",
                description: "Rice, flour, lentils, sugar, salt, cooking oils, and other long-shelf-life pantry staples.",
                icon: "🌾",
                color: "#FF9800",
            },
            {
                name: "Spices & Condiments",
                description: "Whole and ground spices, masala blends, sauces, pickles, and cooking pastes.",
                icon: "🧂",
                color: "#8BC34A",
            },
            {
                name: "Beverages",
                description: "Packaged juices, mineral water, soft drinks, energy drinks, tea, and coffee.",
                icon: "🧃",
                color: "#00BCD4",
            },
            {
                name: "Snacks & Confectionery",
                description: "Chips, namkeen, biscuits, chocolates, sweets, and impulse-buy treats.",
                icon: "🍫",
                color: "#9C27B0",
            },
            {
                name: "Organic & Health Foods",
                description: "Certified organic produce, superfoods, protein bars, health supplements, and diet-specific products.",
                icon: "🌱",
                color: "#388E3C",
            },
            {
                name: "Frozen Foods",
                description: "Frozen vegetables, ready-to-cook meals, ice creams, and chilled convenience foods.",
                icon: "🧊",
                color: "#0288D1",
            },
            {
                name: "Personal Care",
                description: "Soaps, shampoos, skincare, oral care, and personal hygiene products.",
                icon: "🧴",
                color: "#E91E63",
            },
            {
                name: "Household & Cleaning",
                description: "Detergents, dishwash, floor cleaners, trash bags, and household maintenance products.",
                icon: "🧹",
                color: "#607D8B",
            },
        ],
        products: [
            // Fresh Produce
            { name: "Alphonso Mangoes (Season)", category: "Fresh Produce", price: "120", unit: "kg", description: "Premium Devgad Alphonso mangoes — seasonal" },
            { name: "Strawberries", category: "Fresh Produce", price: "80", unit: "pack", description: "250g punnet of fresh strawberries" },
            { name: "Cherry Tomatoes", category: "Fresh Produce", price: "60", unit: "pack", description: "250g pack of vine cherry tomatoes" },
            { name: "Broccoli", category: "Fresh Produce", price: "80", unit: "pcs", description: "Fresh broccoli head — approx 400g" },
            { name: "Baby Spinach", category: "Fresh Produce", price: "50", unit: "pack", description: "100g washed ready-to-eat baby spinach" },
            { name: "Avocado", category: "Fresh Produce", price: "70", unit: "pcs", description: "Ripe Hass avocado" },
            { name: "Zucchini", category: "Fresh Produce", price: "60", unit: "kg", description: "Fresh green zucchini" },
            { name: "Kale", category: "Fresh Produce", price: "60", unit: "bunch", description: "Fresh curly kale bunch" },
            { name: "Blueberries", category: "Fresh Produce", price: "150", unit: "pack", description: "125g fresh blueberries" },
            { name: "Dragon Fruit", category: "Fresh Produce", price: "90", unit: "pcs", description: "Red-flesh dragon fruit — approx 400g" },
            { name: "Sweet Corn", category: "Fresh Produce", price: "30", unit: "pcs", description: "Fresh sweet corn cob" },
            { name: "Button Mushrooms", category: "Fresh Produce", price: "80", unit: "pack", description: "200g fresh button mushrooms" },
            { name: "Lemons", category: "Fresh Produce", price: "60", unit: "kg", description: "Fresh Eureka lemons" },
            { name: "Red Capsicum", category: "Fresh Produce", price: "80", unit: "pcs", description: "Large red capsicum" },
            { name: "Fresh Herbs Pot (Basil)", category: "Fresh Produce", price: "99", unit: "pcs", description: "Live potted basil plant" },
            // Dairy & Eggs
            { name: "Full-Cream Milk (1 ltr)", category: "Dairy & Eggs", price: "72", unit: "ltr", description: "Amul / Mother Dairy full-cream toned milk" },
            { name: "Organic Cow Milk (500ml)", category: "Dairy & Eggs", price: "65", unit: "bottle", description: "A2 organic cow milk — glass bottle" },
            { name: "Greek Yoghurt (400g)", category: "Dairy & Eggs", price: "120", unit: "pcs", description: "Thick strained Greek yoghurt — plain" },
            { name: "Butter (Salted, 100g)", category: "Dairy & Eggs", price: "65", unit: "pcs", description: "Amul / Britannia salted table butter" },
            { name: "Paneer (200g)", category: "Dairy & Eggs", price: "90", unit: "pcs", description: "Fresh soft paneer block" },
            { name: "Mozzarella (200g)", category: "Dairy & Eggs", price: "180", unit: "pcs", description: "Fresh buffalo mozzarella ball" },
            { name: "Aged Cheddar (200g)", category: "Dairy & Eggs", price: "250", unit: "pcs", description: "12-month aged cheddar block" },
            { name: "Free-Range Eggs (6 pcs)", category: "Dairy & Eggs", price: "90", unit: "pack", description: "6-pack cage-free large eggs" },
            { name: "Whipping Cream (200ml)", category: "Dairy & Eggs", price: "110", unit: "pcs", description: "35% fat whipping cream" },
            { name: "Cultured Buttermilk (1 ltr)", category: "Dairy & Eggs", price: "55", unit: "ltr", description: "Spiced masala chaas / buttermilk" },
            // Meat & Seafood
            { name: "Chicken Breast (Boneless, 500g)", category: "Meat & Seafood", price: "160", unit: "pack", description: "Skinless boneless chicken breast — chilled" },
            { name: "Chicken Whole (1 kg)", category: "Meat & Seafood", price: "200", unit: "pcs", description: "Fresh whole chicken — curry cut on request" },
            { name: "Mutton Leg (500g)", category: "Meat & Seafood", price: "400", unit: "pack", description: "Tender bone-in mutton leg pieces" },
            { name: "Salmon Steak (200g)", category: "Meat & Seafood", price: "350", unit: "pcs", description: "Atlantic salmon steak — skin-on" },
            { name: "Tiger Prawns (250g)", category: "Meat & Seafood", price: "320", unit: "pack", description: "Cleaned & deveined tiger prawns — chilled" },
            { name: "Tuna Steak (200g)", category: "Meat & Seafood", price: "280", unit: "pcs", description: "Sushi-grade yellowfin tuna steak" },
            { name: "Sausages (Pork, 6-link)", category: "Meat & Seafood", price: "220", unit: "pack", description: "6-link pork breakfast sausages" },
            // Bakery & Bread
            { name: "Sourdough Loaf", category: "Bakery & Bread", price: "180", unit: "loaf", description: "Artisan naturally leavened sourdough — 400g" },
            { name: "Whole Wheat Sandwich Bread", category: "Bakery & Bread", price: "55", unit: "loaf", description: "Sliced whole wheat loaf — 400g" },
            { name: "Multigrain Bread", category: "Bakery & Bread", price: "70", unit: "loaf", description: "7-grain multigrain sliced loaf" },
            { name: "Croissant (Butter)", category: "Bakery & Bread", price: "60", unit: "pcs", description: "Flaky all-butter croissant" },
            { name: "Blueberry Muffin", category: "Bakery & Bread", price: "80", unit: "pcs", description: "Large fresh-baked blueberry muffin" },
            { name: "Focaccia (Herb)", category: "Bakery & Bread", price: "120", unit: "pcs", description: "Rosemary & sea salt focaccia — 200g" },
            { name: "Baguette", category: "Bakery & Bread", price: "60", unit: "pcs", description: "French-style crusty baguette" },
            { name: "Chocolate Brownie", category: "Bakery & Bread", price: "70", unit: "pcs", description: "Dense fudgy dark chocolate brownie" },
            // Pantry & Dry Goods
            { name: "Basmati Rice (Premium, 1 kg)", category: "Pantry & Dry Goods", price: "120", unit: "kg", description: "Aged extra-long grain basmati rice" },
            { name: "Quinoa (500g)", category: "Pantry & Dry Goods", price: "250", unit: "pack", description: "Organic white quinoa — 500g pack" },
            { name: "Rolled Oats (1 kg)", category: "Pantry & Dry Goods", price: "180", unit: "pack", description: "Old-fashioned whole-grain rolled oats" },
            { name: "Extra Virgin Olive Oil (500ml)", category: "Pantry & Dry Goods", price: "550", unit: "bottle", description: "Cold-pressed EVOO — first press" },
            { name: "Coconut Oil (500ml)", category: "Pantry & Dry Goods", price: "250", unit: "bottle", description: "Cold-pressed virgin coconut oil" },
            { name: "Whole Wheat Atta (5 kg)", category: "Pantry & Dry Goods", price: "280", unit: "bag", description: "Stone-ground whole wheat flour" },
            { name: "Toor Dal (1 kg)", category: "Pantry & Dry Goods", price: "160", unit: "kg", description: "Polished split pigeon peas" },
            { name: "Masoor Dal (500g)", category: "Pantry & Dry Goods", price: "80", unit: "pack", description: "Red split lentils" },
            { name: "Pasta (Spaghetti, 500g)", category: "Pantry & Dry Goods", price: "120", unit: "pack", description: "Durum wheat semolina spaghetti — 500g" },
            { name: "Honey (Raw, 500g)", category: "Pantry & Dry Goods", price: "350", unit: "jar", description: "Unprocessed raw wildflower honey" },
            // Spices & Condiments
            { name: "Turmeric Powder (100g)", category: "Spices & Condiments", price: "60", unit: "pack", description: "Pure Lakadong / Erode turmeric powder" },
            { name: "Kashmiri Red Chilli Powder (100g)", category: "Spices & Condiments", price: "80", unit: "pack", description: "Vibrant colour, mild heat Kashmiri chilli" },
            { name: "Garam Masala (100g)", category: "Spices & Condiments", price: "90", unit: "pack", description: "Freshly blended whole-spice garam masala" },
            { name: "Soy Sauce (200ml)", category: "Spices & Condiments", price: "80", unit: "bottle", description: "Premium dark soy sauce" },
            { name: "Dijon Mustard (200g)", category: "Spices & Condiments", price: "180", unit: "jar", description: "French Dijon mustard" },
            { name: "Sriracha Hot Sauce (200ml)", category: "Spices & Condiments", price: "150", unit: "bottle", description: "Original Huy Fong sriracha chilli sauce" },
            { name: "Pesto (Basil, 190g)", category: "Spices & Condiments", price: "280", unit: "jar", description: "Barilla / artisan basil pesto" },
            { name: "Apple Cider Vinegar (500ml)", category: "Spices & Condiments", price: "220", unit: "bottle", description: "Organic ACV with mother — raw & unfiltered" },
            // Beverages
            { name: "Sparkling Water (1 ltr)", category: "Beverages", price: "80", unit: "bottle", description: "Perrier / San Pellegrino sparkling mineral water" },
            { name: "Cold-Pressed Orange Juice (1 ltr)", category: "Beverages", price: "180", unit: "bottle", description: "100% fresh-squeezed orange juice — no added sugar" },
            { name: "Coconut Water (300ml)", category: "Beverages", price: "50", unit: "pcs", description: "Natural tender coconut water — tetra pack" },
            { name: "Green Tea (25 bags)", category: "Beverages", price: "120", unit: "box", description: "Premium whole-leaf green tea bags" },
            { name: "Cold Brew Coffee (250ml)", category: "Beverages", price: "120", unit: "bottle", description: "Chilled ready-to-drink cold brew coffee" },
            { name: "Kombucha (330ml)", category: "Beverages", price: "150", unit: "bottle", description: "Fermented probiotic kombucha — ginger lemon" },
            { name: "Almond Milk (1 ltr)", category: "Beverages", price: "220", unit: "pack", description: "Unsweetened almond milk — barista edition" },
            { name: "Packaged Mineral Water (1 ltr)", category: "Beverages", price: "25", unit: "bottle", description: "Bisleri / Kinley 1 litre mineral water" },
            // Snacks & Confectionery
            { name: "Dark Chocolate (70%, 100g)", category: "Snacks & Confectionery", price: "180", unit: "pcs", description: "70% single-origin dark chocolate bar" },
            { name: "Mixed Nuts (200g)", category: "Snacks & Confectionery", price: "280", unit: "pack", description: "Roasted unsalted almonds, cashews, walnuts" },
            { name: "Dried Cranberries (100g)", category: "Snacks & Confectionery", price: "120", unit: "pack", description: "Sweetened dried cranberries" },
            { name: "Multigrain Crackers", category: "Snacks & Confectionery", price: "99", unit: "pack", description: "Baked multigrain snack crackers — 100g" },
            { name: "Kettle Chips (Sea Salt)", category: "Snacks & Confectionery", price: "80", unit: "pack", description: "Kettle-cooked sea salt potato crisps — 100g" },
            { name: "Granola Bar", category: "Snacks & Confectionery", price: "50", unit: "pcs", description: "Oat and honey granola bar" },
            { name: "Popcorn (Caramel)", category: "Snacks & Confectionery", price: "120", unit: "pack", description: "Gourmet caramel popcorn — 100g" },
            { name: "Trail Mix (200g)", category: "Snacks & Confectionery", price: "220", unit: "pack", description: "Nuts, seeds, and dried fruit trail mix" },
            // Organic & Health Foods
            { name: "Organic Turmeric Latte Mix (150g)", category: "Organic & Health Foods", price: "299", unit: "pack", description: "Golden milk powder blend — organic spices" },
            { name: "Chia Seeds (250g)", category: "Organic & Health Foods", price: "250", unit: "pack", description: "Organic black chia seeds" },
            { name: "Flax Seeds (250g)", category: "Organic & Health Foods", price: "120", unit: "pack", description: "Cold-milled organic flaxseeds" },
            { name: "Whey Protein (1 kg)", category: "Organic & Health Foods", price: "1800", unit: "pack", description: "Chocolate / vanilla whey protein concentrate" },
            { name: "Organic Jaggery (500g)", category: "Organic & Health Foods", price: "120", unit: "pack", description: "Chemical-free organic cane jaggery" },
            { name: "Spirulina Powder (100g)", category: "Organic & Health Foods", price: "450", unit: "pack", description: "100% pure organic spirulina powder" },
            { name: "Brown Rice (1 kg)", category: "Organic & Health Foods", price: "120", unit: "kg", description: "Unpolished whole-grain brown rice" },
            { name: "Gluten-Free Oats (500g)", category: "Organic & Health Foods", price: "250", unit: "pack", description: "Certified gluten-free rolled oats" },
            // Frozen Foods
            { name: "Frozen Mixed Vegetables (500g)", category: "Frozen Foods", price: "120", unit: "pack", description: "IQF peas, corn, beans, carrots — 500g" },
            { name: "Frozen Edamame (400g)", category: "Frozen Foods", price: "180", unit: "pack", description: "Ready-to-steam salted edamame" },
            { name: "Frozen Pizza (Margherita)", category: "Frozen Foods", price: "350", unit: "pcs", description: "10\" thin-crust margherita pizza — frozen" },
            { name: "Ice Cream (Vanilla, 500ml)", category: "Frozen Foods", price: "250", unit: "pcs", description: "Premium vanilla bean ice cream tub" },
            { name: "Frozen Prawns (500g)", category: "Frozen Foods", price: "350", unit: "pack", description: "IQF cleaned and deveined frozen prawns" },
            { name: "Açaí Pulp (100g)", category: "Frozen Foods", price: "180", unit: "pack", description: "Frozen unsweetened açaí berry pulp sachet" },
            // Personal Care
            { name: "Argan Oil Shampoo (400ml)", category: "Personal Care", price: "380", unit: "bottle", description: "Sulphate-free argan oil shampoo" },
            { name: "Vitamin C Face Wash (100ml)", category: "Personal Care", price: "280", unit: "tube", description: "Brightening vitamin C gel face wash" },
            { name: "Sunscreen SPF 50 (75ml)", category: "Personal Care", price: "350", unit: "tube", description: "Lightweight SPF 50 PA+++ sunscreen" },
            { name: "Natural Deodorant (75g)", category: "Personal Care", price: "320", unit: "pcs", description: "Aluminium-free natural roll-on deodorant" },
            { name: "Bamboo Toothbrush (Pack of 2)", category: "Personal Care", price: "199", unit: "pack", description: "Biodegradable medium-bristle bamboo toothbrush" },
            { name: "Fluoride Toothpaste (150g)", category: "Personal Care", price: "120", unit: "tube", description: "Whitening fluoride toothpaste" },
            { name: "Coconut Body Lotion (200ml)", category: "Personal Care", price: "220", unit: "bottle", description: "Hydrating coconut & shea body lotion" },
            // Household & Cleaning
            { name: "Dishwash Liquid (750ml)", category: "Household & Cleaning", price: "150", unit: "bottle", description: "Concentrated lemon dishwashing liquid" },
            { name: "Floor Cleaner (1 ltr)", category: "Household & Cleaning", price: "120", unit: "bottle", description: "Phenyl-based antibacterial floor cleaner" },
            { name: "Laundry Detergent (1 kg)", category: "Household & Cleaning", price: "180", unit: "pack", description: "Front/top-load liquid detergent — 1 kg" },
            { name: "Trash Bags (19×21\", 30pc)", category: "Household & Cleaning", price: "99", unit: "pack", description: "30-pc medium garbage bags — tie handle" },
            { name: "Kitchen Tissue Roll (2-pack)", category: "Household & Cleaning", price: "120", unit: "pack", description: "2-roll 2-ply kitchen paper towel pack" },
            { name: "Toilet Cleaner Gel (500ml)", category: "Household & Cleaning", price: "99", unit: "bottle", description: "Under-rim thick gel toilet cleaner" },
            { name: "Air Freshener (300ml)", category: "Household & Cleaning", price: "149", unit: "bottle", description: "Floral aerosol room freshener" },
        ],
    },

    {
        name: "Manufacturing / Wholesale",
        emoji: "🏭",
        description: "Raw material and finished goods catalogue for a small manufacturer or wholesale distributor.",
        isSystem: true,
        type: "business",
        categories: [
            {
                name: "Raw Materials",
                description: "Primary inputs sourced from suppliers and used directly in production.",
                icon: "🪨",
                color: "#795548",
            },
            {
                name: "Packaging Materials",
                description: "Boxes, labels, shrink wrap, strapping, and other packaging inputs.",
                icon: "📦",
                color: "#FF9800",
            },
            {
                name: "Finished Goods",
                description: "Completed products ready for dispatch to wholesale or retail buyers.",
                icon: "✅",
                color: "#4CAF50",
            },
            {
                name: "Machinery & Spare Parts",
                description: "Machine components, belts, bearings, and maintenance spare parts.",
                icon: "⚙️",
                color: "#607D8B",
            },
            {
                name: "Chemicals & Consumables",
                description: "Lubricants, solvents, adhesives, and process chemicals used in production.",
                icon: "🧪",
                color: "#9C27B0",
            },
            {
                name: "Safety & PPE",
                description: "Personal protective equipment and safety gear for factory workers.",
                icon: "🦺",
                color: "#F44336",
            },
            {
                name: "Utilities & Fuel",
                description: "Electricity, diesel, LPG, and water used as operational inputs.",
                icon: "⚡",
                color: "#FFC107",
            },
        ],
        products: [
            // Raw Materials
            { name: "Steel Rod (12mm)", category: "Raw Materials", price: "65", unit: "kg", description: "MS steel rod 12mm diameter — per kg" },
            { name: "Aluminium Sheet (2mm)", category: "Raw Materials", price: "250", unit: "kg", description: "2mm aluminium sheet — per kg" },
            { name: "Polypropylene Granules", category: "Raw Materials", price: "120", unit: "kg", description: "Virgin PP granules for injection moulding" },
            { name: "Cotton Yarn (20s)", category: "Raw Materials", price: "280", unit: "kg", description: "20s carded cotton yarn — per kg" },
            { name: "Timber (Teak, per cubic ft)", category: "Raw Materials", price: "2200", unit: "cft", description: "Seasoned teak timber — per cubic foot" },
            { name: "Copper Wire (1mm, 100m)", category: "Raw Materials", price: "1800", unit: "roll", description: "Pure copper winding wire 1mm — 100m roll" },
            { name: "PVC Resin (per MT)", category: "Raw Materials", price: "95000", unit: "mt", description: "Suspension-grade PVC resin per metric tonne" },
            { name: "Cement (50 kg bag)", category: "Raw Materials", price: "350", unit: "bag", description: "OPC 53-grade cement — 50 kg bag" },
            { name: "Sand (per unit)", category: "Raw Materials", price: "1500", unit: "unit", description: "Washed river sand — per unit" },
            // Packaging Materials
            { name: "Corrugated Box (Medium)", category: "Packaging Materials", price: "25", unit: "pcs", description: "3-ply corrugated carton 30×20×15 cm" },
            { name: "Stretch Wrap Roll", category: "Packaging Materials", price: "350", unit: "roll", description: "500mm × 200m machine stretch film" },
            { name: "Bopp Tape (2-inch)", category: "Packaging Materials", price: "45", unit: "roll", description: "48mm × 100m BOPP packing tape" },
            { name: "Shrink Film (PVC)", category: "Packaging Materials", price: "180", unit: "kg", description: "PVC shrink film — per kg" },
            { name: "Product Labels (Roll, 500pc)", category: "Packaging Materials", price: "250", unit: "roll", description: "500-label printed product sticker roll" },
            { name: "Foam Sheet (1m × 2m)", category: "Packaging Materials", price: "120", unit: "sheet", description: "5mm PE foam protective sheet" },
            { name: "Strapping Band Roll", category: "Packaging Materials", price: "500", unit: "roll", description: "PP strapping band 12mm × 1000m roll" },
            // Finished Goods (example category — firm should replace with their actual SKUs)
            { name: "Product SKU-001", category: "Finished Goods", price: "500", unit: "pcs", description: "Standard finished unit — replace with your SKU" },
            { name: "Product SKU-002", category: "Finished Goods", price: "750", unit: "pcs", description: "Premium finished unit — replace with your SKU" },
            { name: "Bulk Carton (24 units)", category: "Finished Goods", price: "12000", unit: "carton", description: "Dispatch carton of 24 finished units" },
            // Machinery & Spare Parts
            { name: "V-Belt (A-Section)", category: "Machinery & Spare Parts", price: "350", unit: "pcs", description: "A-section V-belt for standard drives" },
            { name: "Ball Bearing (6205)", category: "Machinery & Spare Parts", price: "250", unit: "pcs", description: "6205-ZZ deep-groove ball bearing" },
            { name: "Industrial Filter (Air)", category: "Machinery & Spare Parts", price: "800", unit: "pcs", description: "Compressed-air inline filter element" },
            { name: "Conveyor Belt (per metre)", category: "Machinery & Spare Parts", price: "600", unit: "mtr", description: "PVC conveyor belt — per linear metre" },
            { name: "Motor Capacitor (25µF)", category: "Machinery & Spare Parts", price: "180", unit: "pcs", description: "25µF run capacitor for single-phase motors" },
            // Chemicals & Consumables
            { name: "Cutting Oil (5 ltr)", category: "Chemicals & Consumables", price: "650", unit: "can", description: "Mineral-based metal cutting oil — 5 ltr can" },
            { name: "Industrial Adhesive (1 kg)", category: "Chemicals & Consumables", price: "450", unit: "pcs", description: "Contact adhesive / rubber cement — 1 kg" },
            { name: "Rust Inhibitor Spray", category: "Chemicals & Consumables", price: "280", unit: "bottle", description: "400ml corrosion-protection spray" },
            { name: "Solvent (IPA, 1 ltr)", category: "Chemicals & Consumables", price: "250", unit: "bottle", description: "99% isopropyl alcohol — 1 ltr bottle" },
            { name: "Grease (EP2, 1 kg)", category: "Chemicals & Consumables", price: "350", unit: "pcs", description: "EP2 lithium grease for bearings — 1 kg tin" },
            // Safety & PPE
            { name: "Safety Helmet", category: "Safety & PPE", price: "250", unit: "pcs", description: "HDPE ISI-marked safety helmet" },
            { name: "Safety Shoes (Steel Toe)", category: "Safety & PPE", price: "1200", unit: "pair", description: "Steel-toe leather safety shoe — sizes 6–11" },
            { name: "Safety Gloves (Nitrile)", category: "Safety & PPE", price: "180", unit: "box", description: "100-pc powder-free nitrile gloves — M/L" },
            { name: "Safety Goggles", category: "Safety & PPE", price: "150", unit: "pcs", description: "Anti-fog polycarbonate safety goggles" },
            { name: "Hi-Vis Jacket", category: "Safety & PPE", price: "350", unit: "pcs", description: "High-visibility reflective safety vest" },
            { name: "Ear Plugs (Disposable, 50 pr)", category: "Safety & PPE", price: "120", unit: "pack", description: "50-pair foam disposable ear plugs" },
            // Utilities & Fuel
            { name: "Diesel (per litre)", category: "Utilities & Fuel", price: "92", unit: "ltr", description: "High-speed diesel for generators and vehicles" },
            { name: "LPG (Commercial, 19 kg)", category: "Utilities & Fuel", price: "1750", unit: "cylinder", description: "19 kg commercial LPG cylinder" },
            { name: "Electricity (per unit)", category: "Utilities & Fuel", price: "8", unit: "unit", description: "Industrial electricity — per kWh unit" },
        ],
    },
];
