export const systemTemplates = [
    // ── Personal ──────────────────────────────────────────────────────────────
    {
        name: "Basic Grocery",
        emoji: "🛒",
        description: "A starter template for everyday grocery shopping.",
        isSystem: true,
        type: "personal",
        categories: [
            { name: "Fruits & Vegetables", icon: "🥦", color: "#4CAF50" },
            { name: "Dairy", icon: "🥛", color: "#2196F3" },
            { name: "Bakery", icon: "🍞", color: "#FF9800" },
            { name: "Meat & Seafood", icon: "🥩", color: "#F44336" },
            { name: "Beverages", icon: "🧃", color: "#9C27B0" },
            { name: "Snacks", icon: "🍿", color: "#FF5722" },
            { name: "Cleaning", icon: "🧹", color: "#607D8B" },
        ],
        products: [
            { name: "Apples", category: "Fruits & Vegetables", price: "2.99", unit: "kg" },
            { name: "Bananas", category: "Fruits & Vegetables", price: "1.49", unit: "bunch" },
            { name: "Spinach", category: "Fruits & Vegetables", price: "1.99", unit: "bag" },
            { name: "Milk", category: "Dairy", price: "3.49", unit: "liter" },
            { name: "Butter", category: "Dairy", price: "4.99", unit: "pack" },
            { name: "Cheddar Cheese", category: "Dairy", price: "5.99", unit: "pack" },
            { name: "Bread", category: "Bakery", price: "2.49", unit: "loaf" },
            { name: "Eggs", category: "Dairy", price: "3.99", unit: "dozen" },
            { name: "Chicken Breast", category: "Meat & Seafood", price: "7.99", unit: "kg" },
            { name: "Orange Juice", category: "Beverages", price: "3.99", unit: "liter" },
            { name: "Chips", category: "Snacks", price: "2.99", unit: "bag" },
            { name: "Dish Soap", category: "Cleaning", price: "2.49", unit: "bottle" },
        ],
    },
    {
        name: "Meal Prep",
        emoji: "🍱",
        description: "Optimised for weekly meal prepping.",
        isSystem: true,
        type: "personal",
        categories: [
            { name: "Proteins", icon: "🥩", color: "#F44336" },
            { name: "Grains", icon: "🌾", color: "#FF9800" },
            { name: "Vegetables", icon: "🥦", color: "#4CAF50" },
            { name: "Sauces & Spices", icon: "🧂", color: "#795548" },
            { name: "Oils & Fats", icon: "🫙", color: "#FFC107" },
        ],
        products: [
            { name: "Chicken Thighs", category: "Proteins", price: "6.99", unit: "kg" },
            { name: "Ground Turkey", category: "Proteins", price: "7.49", unit: "kg" },
            { name: "Salmon Fillet", category: "Proteins", price: "12.99", unit: "kg" },
            { name: "Brown Rice", category: "Grains", price: "3.49", unit: "kg" },
            { name: "Quinoa", category: "Grains", price: "5.99", unit: "kg" },
            { name: "Oats", category: "Grains", price: "2.99", unit: "kg" },
            { name: "Broccoli", category: "Vegetables", price: "1.99", unit: "head" },
            { name: "Sweet Potato", category: "Vegetables", price: "2.49", unit: "kg" },
            { name: "Bell Peppers", category: "Vegetables", price: "3.49", unit: "pack" },
            { name: "Olive Oil", category: "Oils & Fats", price: "8.99", unit: "bottle" },
            { name: "Soy Sauce", category: "Sauces & Spices", price: "2.99", unit: "bottle" },
            { name: "Garlic Powder", category: "Sauces & Spices", price: "1.99", unit: "jar" },
        ],
    },
    {
        name: "Home & Household",
        emoji: "🏠",
        description: "Everything you need to run a home smoothly.",
        isSystem: true,
        type: "personal",
        categories: [
            { name: "Cleaning Supplies", icon: "🧹", color: "#607D8B" },
            { name: "Toiletries", icon: "🧴", color: "#E91E63" },
            { name: "Kitchen", icon: "🍳", color: "#FF9800" },
            { name: "Laundry", icon: "👕", color: "#2196F3" },
            { name: "Electronics", icon: "🔌", color: "#9C27B0" },
        ],
        products: [
            { name: "Shampoo", category: "Toiletries", price: "5.99", unit: "bottle" },
            { name: "Toothpaste", category: "Toiletries", price: "2.99", unit: "tube" },
            { name: "Toilet Paper", category: "Toiletries", price: "8.99", unit: "pack" },
            { name: "Detergent", category: "Laundry", price: "12.99", unit: "box" },
            { name: "Fabric Softener", category: "Laundry", price: "6.99", unit: "bottle" },
            { name: "Dishwasher Pods", category: "Kitchen", price: "9.99", unit: "pack" },
            { name: "Trash Bags", category: "Cleaning Supplies", price: "4.99", unit: "roll" },
            { name: "All-Purpose Cleaner", category: "Cleaning Supplies", price: "3.99", unit: "bottle" },
            { name: "Light Bulbs", category: "Electronics", price: "7.99", unit: "pack" },
        ],
    },

    // ── Business ──────────────────────────────────────────────────────────────
    {
        name: "Retail Shop",
        emoji: "🏪",
        description: "Track inventory and purchases for a retail store.",
        isSystem: true,
        type: "business",
        categories: [
            { name: "Electronics", icon: "📱", color: "#2196F3" },
            { name: "Clothing", icon: "👗", color: "#E91E63" },
            { name: "Accessories", icon: "💍", color: "#FF9800" },
            { name: "Packaging", icon: "📦", color: "#795548" },
            { name: "Stationery", icon: "📝", color: "#607D8B" },
        ],
        products: [
            { name: "Carry Bags", category: "Packaging", price: "0.50", unit: "piece" },
            { name: "Receipt Paper Roll", category: "Stationery", price: "2.99", unit: "roll" },
            { name: "Price Tags", category: "Stationery", price: "3.99", unit: "pack" },
            { name: "Bubble Wrap", category: "Packaging", price: "8.99", unit: "roll" },
            { name: "Tape Gun", category: "Packaging", price: "5.99", unit: "piece" },
        ],
    },
    {
        name: "Restaurant / Café",
        emoji: "☕",
        description: "Manage kitchen supplies and ingredients for food service.",
        isSystem: true,
        type: "business",
        categories: [
            { name: "Produce", icon: "🥦", color: "#4CAF50" },
            { name: "Meat & Fish", icon: "🥩", color: "#F44336" },
            { name: "Dairy & Eggs", icon: "🥛", color: "#2196F3" },
            { name: "Dry Goods", icon: "🌾", color: "#FF9800" },
            { name: "Beverages", icon: "☕", color: "#795548" },
            { name: "Disposables", icon: "🥤", color: "#607D8B" },
        ],
        products: [
            { name: "Coffee Beans", category: "Beverages", price: "24.99", unit: "kg" },
            { name: "Whole Milk", category: "Dairy & Eggs", price: "1.99", unit: "liter" },
            { name: "Sugar", category: "Dry Goods", price: "1.49", unit: "kg" },
            { name: "Disposable Cups", category: "Disposables", price: "12.99", unit: "pack" },
            { name: "Napkins", category: "Disposables", price: "4.99", unit: "pack" },
            { name: "All-Purpose Flour", category: "Dry Goods", price: "2.99", unit: "kg" },
            { name: "Olive Oil", category: "Dry Goods", price: "9.99", unit: "bottle" },
        ],
    },
    {
        name: "Office Supplies",
        emoji: "🖥️",
        description: "Keep your office stocked and organised.",
        isSystem: true,
        type: "business",
        categories: [
            { name: "Stationery", icon: "✏️", color: "#607D8B" },
            { name: "Tech & Peripherals", icon: "💻", color: "#2196F3" },
            { name: "Furniture", icon: "🪑", color: "#795548" },
            { name: "Pantry", icon: "☕", color: "#FF9800" },
            { name: "Cleaning", icon: "🧹", color: "#4CAF50" },
        ],
        products: [
            { name: "A4 Paper Ream", category: "Stationery", price: "5.99", unit: "ream" },
            { name: "Ballpoint Pens", category: "Stationery", price: "3.99", unit: "pack" },
            { name: "Sticky Notes", category: "Stationery", price: "2.99", unit: "pack" },
            { name: "HDMI Cable", category: "Tech & Peripherals", price: "12.99", unit: "piece" },
            { name: "USB Hub", category: "Tech & Peripherals", price: "24.99", unit: "piece" },
            { name: "Coffee Pods", category: "Pantry", price: "9.99", unit: "pack" },
            { name: "Hand Sanitiser", category: "Cleaning", price: "4.99", unit: "bottle" },
        ],
    },
    {
        name: "Freelancer Starter",
        emoji: "💼",
        description: "Track tools and subscriptions for solo professionals.",
        isSystem: true,
        type: "business",
        categories: [
            { name: "Software", icon: "💻", color: "#2196F3" },
            { name: "Hardware", icon: "🖥️", color: "#607D8B" },
            { name: "Office", icon: "📋", color: "#FF9800" },
            { name: "Marketing", icon: "📣", color: "#E91E63" },
        ],
        products: [
            { name: "Domain Renewal", category: "Software", price: "14.99", unit: "year" },
            { name: "Cloud Storage", category: "Software", price: "9.99", unit: "month" },
            { name: "Notebook", category: "Office", price: "4.99", unit: "piece" },
            { name: "Business Cards", category: "Marketing", price: "19.99", unit: "pack" },
            { name: "External SSD", category: "Hardware", price: "79.99", unit: "piece" },
        ],
    },
];
