import { getTemplateStyles } from "./templateStyles.js";

export const renderSOHtml = (so, group) => {
    const fmt = (n) =>
        new Intl.NumberFormat("en-IN", { style: "currency", currency: so.customer?.currency || "INR" }).format(n || 0);

    const rows = (so.items || [])
        .map(
            (it, i) => `
        <tr class="${i % 2 === 0 ? "even" : ""}">
            <td>${it.product?.name || it.description || "—"}</td>
            <td class="center">${it.qty ?? "—"} ${it.unit || ""}</td>
            <td class="right">${fmt(it.unitPrice)}</td>
            <td class="center">${it.taxRate ?? 0}%</td>
            <td class="right">${fmt(it.amount)}</td>
        </tr>`
        )
        .join("");

    const deliveryDate = so.deliveryDate
        ? new Date(so.deliveryDate).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })
        : "—";

    const createdDate = new Date(so.createdAt).toLocaleDateString("en-IN", {
        day: "2-digit", month: "short", year: "numeric",
    });

    const tmpl = group?.businessDetails?.orderTemplate || group?.businessDetails?.template || "classic";
    const needsBody = tmpl === "modern" || tmpl === "executive";
    const modern = tmpl === "modern";
    const bodyOpen = needsBody ? '<div class="body">' : "";
    const bodyClose = needsBody ? "</div>" : "";
    const divider = needsBody ? "" : '<div class="divider"></div>';
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<style>${getTemplateStyles(tmpl, group?.businessDetails?.color)}</style>
</head>
<body>
<div class="page">

  <div class="doc-header">
    <div class="brand" style="display:flex;align-items:center;gap:16px;">
      ${group?.businessDetails?.logo ? `<img src="${group.businessDetails.logo}" style="height:64px;width:64px;object-fit:contain;border-radius:8px;flex-shrink:0;" />` : ""}
      <div>${group?.businessDetails?.legalName || group?.name || "OpenLedger"}<span>Sales Order</span></div>
    </div>
    <div class="doc-meta">
      <div class="doc-number">${so.soNumber}</div>
      <div class="doc-date">Issued ${createdDate}</div>
      <span class="status-badge">${so.status || "draft"}</span>
    </div>
  </div>

  ${bodyOpen}
  ${divider}

  <div class="parties">
    <div class="party-card">
      <div class="party-label">From</div>
      <div class="party-name">${group?.businessDetails?.legalName || group?.name || "—"}</div>
      ${group?.businessDetails?.gstin ? `<div class="party-detail">GSTIN: ${group.businessDetails.gstin}</div>` : ""}
      ${group?.businessDetails?.email || group?.email ? `<div class="party-detail">${group?.businessDetails?.email || group.email}</div>` : ""}
      ${group?.businessDetails?.addressLine1 ? `<div class="party-detail">${[group.businessDetails.addressLine1, group.businessDetails.city, group.businessDetails.state, group.businessDetails.pincode].filter(Boolean).join(", ")}</div>` : (group?.address ? `<div class="party-detail">${group.address}</div>` : "")}
    </div>
    <div class="party-card">
      <div class="party-label">To (Customer)</div>
      <div class="party-name">${so.customer?.name || "—"}</div>
      ${so.customer?.gstin ? `<div class="party-detail">GSTIN: ${so.customer.gstin}</div>` : ""}
      ${so.customer?.email ? `<div class="party-detail">${so.customer.email}</div>` : ""}
      ${so.customer?.address ? `<div class="party-detail">${so.customer.address}</div>` : ""}
    </div>
  </div>

  <div class="dates">
    <div class="date-item">
      <div class="date-label">Order Date</div>
      <div class="date-value">${createdDate}</div>
    </div>
    <div class="date-item">
      <div class="date-label">Expected Delivery</div>
      <div class="date-value">${deliveryDate}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Product / Description</th>
        <th class="center">Qty</th>
        <th class="right">Unit Price</th>
        <th class="center">Tax</th>
        <th class="right">Amount</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="totals">
    <div class="totals-box">
      <div class="totals-row"><span>Subtotal</span><span>${fmt(so.subtotal)}</span></div>
      <div class="totals-row"><span>Tax</span><span>${fmt(so.taxAmount)}</span></div>
      <div class="totals-row grand"><span>Grand Total</span><span>${fmt(so.grandTotal)}</span></div>
    </div>
  </div>

  ${so.notes ? `
  <div class="notes-section">
    <div class="notes-label">Notes</div>
    <div class="notes-text">${so.notes}</div>
  </div>` : ""}

  <div class="footer">
    <span class="footer-note">Generated by OpenLedger · ${new Date().toLocaleDateString("en-IN")}</span>
    <span class="footer-note">This is a computer-generated document.</span>
  </div>

  ${bodyClose}
</div>
</body>
</html>`;
};
